### ISSUE TITLE
Target Branch Missing (Question)

### ISSUE THREAD

**Issue by ryanlabouve** [jagthedrummer/ember-cli-deploy-github-pages#1]
If a user had not yes pushed an initial `gh-pages` branch on remote, would this throw an error?

https://github.com/jagthedrummer/ember-cli-deploy-github-pages/blob/master/index.js#L44

```
if(!targetBranchExists){
  plugin.log("Missing branch " + targetBranch, {color:'red'});
}
```

**Comment by jagthedrummer** [comment]
This would throw the error if the target branch does not yet exist locally.

**Comment by jagthedrummer** [comment]
It would be nice if we could either create the branch if it's missing or output some instructions for the user on how to do so.

In addition to creating the branch we (or the user) should create a `.gitignore` file in the target branch that contains:

```
node_modules
bower_components
tmp
```
